"""
Prepare and score a complete manual review of private validation errors.

This script works with the predictions already generated by:

    analyze_private_errors.py

No GPT-2 inference is required again.

Two modes are available:

    prepare
        Creates one CSV containing ALL private validation errors.
        Existing manual decisions from manual_review_sample.csv are
        imported automatically.

    score
        Reads the completed manual review and recalculates the
        private validation metrics using the manually adjudicated
        labels.

Usage:

    python -m spam_detector.review_private_errors prepare

    python -m spam_detector.review_private_errors score
"""

import argparse
import json

import pandas as pd
from sklearn.metrics import (
    accuracy_score,
    average_precision_score,
    confusion_matrix,
    f1_score,
    precision_score,
    recall_score,
    roc_auc_score,
)

from spam_detector.paths import (
    DATA_DIR,
    PROJECT_ROOT,
)

# Labels

HAM_LABEL = 0
SPAM_LABEL = 1


# Input directory

ERROR_ANALYSIS_DIR = (
    DATA_DIR
    / "private_error_analysis"
)


# Existing prediction file

ALL_PREDICTIONS_FILE = (
    ERROR_ANALYSIS_DIR
    / "all_predictions.csv"
)


# Existing manually reviewed sample

MANUAL_SAMPLE_FILE = (
    ERROR_ANALYSIS_DIR
    / "manual_review_sample.csv"
)


# New complete manual review file

FULL_REVIEW_FILE = (
    ERROR_ANALYSIS_DIR
    / "all_errors_for_review.csv"
)


# Complete adjudicated predictions

ADJUDICATED_PREDICTIONS_FILE = (
    ERROR_ANALYSIS_DIR
    / "all_predictions_adjudicated.csv"
)


# Result directory

RESULTS_DIR = (
    PROJECT_ROOT
    / "results"
)


# Corrected evaluation results

CORRECTED_RESULTS_FILE = (
    RESULTS_DIR
    / "private_validation_corrected_metrics.json"
)


def normalize_manual_label(
    value,
):
    """
    Convert different manual label spellings to numeric labels.

    Accepted spam values include:

        Spam
        SPAM
        spam
        1

    Accepted ham values include:

        No Spam
        NoSpam
        Ham
        ham
        0

    Empty or unknown values return None.
    """

    if pd.isna(
        value
    ):
        return None

    text = str(
        value
    ).strip().lower()

    text = (
        text
        .replace("_", " ")
        .replace("-", " ")
    )

    text = " ".join(
        text.split()
    )

    spam_values = {
        "spam",
        "1",
        "yes spam",
        "is spam",
    }

    ham_values = {
        "no spam",
        "nospam",
        "not spam",
        "ham",
        "0",
        "no",
    }

    if text in spam_values:
        return SPAM_LABEL

    if text in ham_values:
        return HAM_LABEL

    return None


def readable_label(
    label: int,
) -> str:
    """
    Convert numeric labels into readable labels.
    """

    if label == SPAM_LABEL:
        return "Spam"

    if label == HAM_LABEL:
        return "No Spam"

    return "Unknown"


def find_existing_manual_column(
    dataframe: pd.DataFrame,
):
    """
    Detect the column containing previous manual review decisions.

    This also handles Excel-created columns such as:

        Unnamed: 21
        Unnamed: 22

    Only columns whose names suggest manual review or unnamed
    extra spreadsheet columns are considered.
    """

    candidates = []

    for column in dataframe.columns:

        column_lower = str(
            column
        ).lower()

        if (
            "manual" in column_lower
            or "review" in column_lower
            or column_lower.startswith(
                "unnamed:"
            )
        ):

            recognized_count = (
                dataframe[
                    column
                ]
                .apply(
                    normalize_manual_label
                )
                .notna()
                .sum()
            )

            candidates.append(
                (
                    column,
                    int(
                        recognized_count
                    ),
                )
            )

    if not candidates:
        return None

    candidates.sort(
        key=lambda item: item[1],
        reverse=True,
    )

    best_column = candidates[
        0
    ][0]

    best_count = candidates[
        0
    ][1]

    if best_count == 0:
        return None

    print(
        f"Detected previous manual review column: "
        f"{best_column}"
    )

    print(
        f"Recognized manual decisions: "
        f"{best_count}"
    )

    return best_column


def load_previous_manual_decisions() -> dict:
    """
    Load previous decisions from manual_review_sample.csv.

    Returns a dictionary:

        row_id -> numeric manual label
    """

    decisions = {}

    if not MANUAL_SAMPLE_FILE.exists():

        print(
            "\nNo previous manual review sample found."
        )

        return decisions

    sample = pd.read_csv(
        MANUAL_SAMPLE_FILE
    )

    if "row_id" not in sample.columns:

        print(
            "\nPrevious manual review file has no row_id column."
        )

        return decisions

    manual_column = (
        find_existing_manual_column(
            sample
        )
    )

    if manual_column is None:

        print(
            "\nNo previous manual decisions detected."
        )

        return decisions

    for _, row in sample.iterrows():

        manual_label = (
            normalize_manual_label(
                row[
                    manual_column
                ]
            )
        )

        if manual_label is None:
            continue

        row_id = int(
            row[
                "row_id"
            ]
        )

        decisions[
            row_id
        ] = manual_label

    print(
        f"Imported previous decisions: "
        f"{len(decisions)}"
    )

    return decisions


def preserve_existing_review(
    review_dataframe: pd.DataFrame,
) -> dict:
    """
    Preserve manual decisions if all_errors_for_review.csv already
    exists.

    This prevents accidental loss of review progress when prepare
    is run more than once.
    """

    decisions = {}

    if not FULL_REVIEW_FILE.exists():
        return decisions

    existing = pd.read_csv(
        FULL_REVIEW_FILE
    )

    if (
        "row_id" not in existing.columns
        or "manual_review" not in existing.columns
    ):
        return decisions

    for _, row in existing.iterrows():

        manual_label = (
            normalize_manual_label(
                row[
                    "manual_review"
                ]
            )
        )

        if manual_label is None:
            continue

        row_id = int(
            row[
                "row_id"
            ]
        )

        decisions[
            row_id
        ] = manual_label

    if decisions:

        print(
            f"Preserving existing full-review decisions: "
            f"{len(decisions)}"
        )

    return decisions


def prepare_review_file() -> None:
    """
    Create a CSV containing all private validation errors.

    Existing manual review decisions are imported automatically.
    """

    if not ALL_PREDICTIONS_FILE.exists():

        raise FileNotFoundError(
            f"Prediction file not found:\n"
            f"{ALL_PREDICTIONS_FILE}\n\n"
            f"Run analyze_private_errors.py first."
        )

    predictions = pd.read_csv(
        ALL_PREDICTIONS_FILE
    )

    required_columns = {
        "row_id",
        "true_label",
        "predicted_label",
        "error_type",
        "spam_probability",
        "model_confidence",
    }

    missing_columns = (
        required_columns
        - set(
            predictions.columns
        )
    )

    if missing_columns:

        raise ValueError(
            "Missing required columns: "
            f"{sorted(missing_columns)}"
        )

    errors = predictions[
        predictions[
            "true_label"
        ]
        != predictions[
            "predicted_label"
        ]
    ].copy()

    previous_sample_decisions = (
        load_previous_manual_decisions()
    )

    existing_review_decisions = (
        preserve_existing_review(
            errors
        )
    )

    # Existing full review decisions take priority over the
    # original 20-example sample.

    combined_decisions = {
        **previous_sample_decisions,
        **existing_review_decisions,
    }

    errors[
        "original_label"
    ] = errors[
        "true_label"
    ].apply(
        readable_label
    )

    errors[
        "model_prediction"
    ] = errors[
        "predicted_label"
    ].apply(
        readable_label
    )

    manual_values = []

    for row_id in errors[
        "row_id"
    ]:

        row_id = int(
            row_id
        )

        if row_id in combined_decisions:

            manual_values.append(
                readable_label(
                    combined_decisions[
                        row_id
                    ]
                )
            )

        else:

            manual_values.append(
                ""
            )

    errors[
        "manual_review"
    ] = manual_values

    errors[
        "review_notes"
    ] = ""

    # Preserve existing notes if present.

    if FULL_REVIEW_FILE.exists():

        old_review = pd.read_csv(
            FULL_REVIEW_FILE
        )

        if (
            "row_id" in old_review.columns
            and "review_notes" in old_review.columns
        ):

            notes_by_row = {}

            for _, row in old_review.iterrows():

                note = row[
                    "review_notes"
                ]

                if pd.isna(
                    note
                ):
                    continue

                note = str(
                    note
                ).strip()

                if not note:
                    continue

                notes_by_row[
                    int(
                        row[
                            "row_id"
                        ]
                    )
                ] = note

            errors[
                "review_notes"
            ] = errors[
                "row_id"
            ].apply(
                lambda row_id:
                    notes_by_row.get(
                        int(
                            row_id
                        ),
                        "",
                    )
            )

    preferred_columns = [
        "row_id",
        "error_type",
        "review_priority",
        "original_label",
        "model_prediction",
        "spam_probability",
        "ham_probability",
        "model_confidence",
        "sender",
        "subject",
        "body_preview",
        "date",
        "source",
        "source_split",
        "manual_review",
        "review_notes",
    ]

    available_columns = [
        column
        for column in preferred_columns
        if column in errors.columns
    ]

    review = errors[
        available_columns
    ].copy()

    # Show false negatives first because missing spam is usually
    # particularly relevant for a spam filter.

    error_order = {
        "false_negative":
            0,

        "false_positive":
            1,
    }

    review[
        "_error_order"
    ] = review[
        "error_type"
    ].map(
        error_order
    ).fillna(
        2
    )

    review = (
        review
        .sort_values(
            by=[
                "_error_order",
                "model_confidence",
            ],
            ascending=[
                True,
                False,
            ],
        )
        .drop(
            columns=[
                "_error_order"
            ]
        )
        .reset_index(
            drop=True
        )
    )

    ERROR_ANALYSIS_DIR.mkdir(
        parents=True,
        exist_ok=True,
    )

    review.to_csv(
        FULL_REVIEW_FILE,
        index=False,
        encoding="utf-8-sig",
    )

    total_errors = len(
        review
    )

    reviewed = (
        review[
            "manual_review"
        ]
        .apply(
            normalize_manual_label
        )
        .notna()
        .sum()
    )

    remaining = (
        total_errors
        - reviewed
    )

    false_negatives = int(
        (
            review[
                "error_type"
            ]
            == "false_negative"
        ).sum()
    )

    false_positives = int(
        (
            review[
                "error_type"
            ]
            == "false_positive"
        ).sum()
    )

    print(
        "\nFull private error review prepared"
    )

    print(
        "-" * 60
    )

    print(
        f"Total model disagreements: "
        f"{total_errors}"
    )

    print(
        f"False negatives: "
        f"{false_negatives}"
    )

    print(
        f"False positives: "
        f"{false_positives}"
    )

    print(
        f"Already manually reviewed: "
        f"{reviewed}"
    )

    print(
        f"Still requiring review: "
        f"{remaining}"
    )

    print(
        "-" * 60
    )

    print(
        "\nReview file:"
    )

    print(
        FULL_REVIEW_FILE
    )

    print(
        "\nFill only the column:"
    )

    print(
        "manual_review"
    )

    print(
        "\nUse exactly:"
    )

    print(
        "Spam"
    )

    print(
        "or"
    )

    print(
        "No Spam"
    )


def calculate_metrics(
    labels,
    predictions,
    spam_probabilities,
) -> dict:
    """
    Calculate binary classification metrics.
    """

    accuracy = accuracy_score(
        labels,
        predictions,
    )

    precision = precision_score(
        labels,
        predictions,
        pos_label=SPAM_LABEL,
        zero_division=0,
    )

    recall = recall_score(
        labels,
        predictions,
        pos_label=SPAM_LABEL,
        zero_division=0,
    )

    f1 = f1_score(
        labels,
        predictions,
        pos_label=SPAM_LABEL,
        zero_division=0,
    )

    confusion = confusion_matrix(
        labels,
        predictions,
        labels=[
            HAM_LABEL,
            SPAM_LABEL,
        ],
    )

    (
        true_negatives,
        false_positives,
        false_negatives,
        true_positives,
    ) = confusion.ravel()

    unique_labels = set(
        labels
    )

    if len(
        unique_labels
    ) == 2:

        roc_auc = roc_auc_score(
            labels,
            spam_probabilities,
        )

        pr_auc = average_precision_score(
            labels,
            spam_probabilities,
        )

    else:

        roc_auc = None
        pr_auc = None

    return {
        "examples":
            int(
                len(
                    labels
                )
            ),

        "ham_examples":
            int(
                sum(
                    label == HAM_LABEL
                    for label in labels
                )
            ),

        "spam_examples":
            int(
                sum(
                    label == SPAM_LABEL
                    for label in labels
                )
            ),

        "accuracy":
            float(
                accuracy
            ),

        "spam_precision":
            float(
                precision
            ),

        "spam_recall":
            float(
                recall
            ),

        "spam_f1":
            float(
                f1
            ),

        "roc_auc":
            (
                float(
                    roc_auc
                )
                if roc_auc is not None
                else None
            ),

        "pr_auc":
            (
                float(
                    pr_auc
                )
                if pr_auc is not None
                else None
            ),

        "confusion_matrix": {
            "true_negatives":
                int(
                    true_negatives
                ),

            "false_positives":
                int(
                    false_positives
                ),

            "false_negatives":
                int(
                    false_negatives
                ),

            "true_positives":
                int(
                    true_positives
                ),
        },
    }


def print_metrics(
    title: str,
    metrics: dict,
) -> None:
    """
    Print classification metrics.
    """

    print(
        f"\n{title}"
    )

    print(
        "-" * 60
    )

    print(
        f"Examples: "
        f"{metrics['examples']:,}"
    )

    print(
        f"Ham: "
        f"{metrics['ham_examples']:,}"
    )

    print(
        f"Spam: "
        f"{metrics['spam_examples']:,}"
    )

    print(
        f"Accuracy: "
        f"{metrics['accuracy'] * 100:.2f}%"
    )

    print(
        f"Spam precision: "
        f"{metrics['spam_precision'] * 100:.2f}%"
    )

    print(
        f"Spam recall: "
        f"{metrics['spam_recall'] * 100:.2f}%"
    )

    print(
        f"Spam F1: "
        f"{metrics['spam_f1'] * 100:.2f}%"
    )

    if metrics[
        "roc_auc"
    ] is not None:

        print(
            f"ROC-AUC: "
            f"{metrics['roc_auc']:.6f}"
        )

    if metrics[
        "pr_auc"
    ] is not None:

        print(
            f"PR-AUC: "
            f"{metrics['pr_auc']:.6f}"
        )

    confusion = metrics[
        "confusion_matrix"
    ]

    print(
        "\nConfusion matrix"
    )

    print(
        f"True negatives:  "
        f"{confusion['true_negatives']:,}"
    )

    print(
        f"False positives: "
        f"{confusion['false_positives']:,}"
    )

    print(
        f"False negatives: "
        f"{confusion['false_negatives']:,}"
    )

    print(
        f"True positives:  "
        f"{confusion['true_positives']:,}"
    )

    print(
        "-" * 60
    )


def score_completed_review() -> None:
    """
    Recalculate private validation metrics after all model
    disagreements have been manually reviewed.

    For model disagreements:
        the manual label replaces the original dataset label.

    For model agreements:
        the existing original label is retained.

    This produces an adjudicated evaluation of the private
    validation set.
    """

    if not ALL_PREDICTIONS_FILE.exists():

        raise FileNotFoundError(
            f"Prediction file not found:\n"
            f"{ALL_PREDICTIONS_FILE}"
        )

    if not FULL_REVIEW_FILE.exists():

        raise FileNotFoundError(
            f"Full review file not found:\n"
            f"{FULL_REVIEW_FILE}\n\n"
            f"Run prepare mode first."
        )

    predictions = pd.read_csv(
        ALL_PREDICTIONS_FILE
    )

    review = pd.read_csv(
        FULL_REVIEW_FILE
    )

    if "manual_review" not in review.columns:

        raise ValueError(
            "The review file does not contain "
            "'manual_review'."
        )

    review[
        "manual_label_numeric"
    ] = review[
        "manual_review"
    ].apply(
        normalize_manual_label
    )

    unresolved = review[
        review[
            "manual_label_numeric"
        ].isna()
    ]

    if len(
        unresolved
    ) > 0:

        print(
            "\nManual review is not complete."
        )

        print(
            f"Remaining rows: "
            f"{len(unresolved)}"
        )

        print(
            "\nUnresolved row IDs:"
        )

        print(
            unresolved[
                "row_id"
            ].tolist()
        )

        print(
            "\nComplete these rows in:"
        )

        print(
            FULL_REVIEW_FILE
        )

        return

    manual_labels = {
        int(
            row[
                "row_id"
            ]
        ):
        int(
            row[
                "manual_label_numeric"
            ]
        )

        for _, row in review.iterrows()
    }

    predictions[
        "corrected_label"
    ] = predictions[
        "true_label"
    ].astype(
        int
    )

    predictions[
        "manually_reviewed"
    ] = False

    for index, row in predictions.iterrows():

        row_id = int(
            row[
                "row_id"
            ]
        )

        if row_id not in manual_labels:
            continue

        predictions.at[
            index,
            "corrected_label"
        ] = manual_labels[
            row_id
        ]

        predictions.at[
            index,
            "manually_reviewed"
        ] = True

    predictions[
        "label_changed"
    ] = (
        predictions[
            "corrected_label"
        ]
        != predictions[
            "true_label"
        ]
    )

    predictions[
        "correct_after_review"
    ] = (
        predictions[
            "predicted_label"
        ]
        == predictions[
            "corrected_label"
        ]
    )

    original_metrics = (
        calculate_metrics(
            labels=predictions[
                "true_label"
            ].astype(
                int
            ).tolist(),

            predictions=predictions[
                "predicted_label"
            ].astype(
                int
            ).tolist(),

            spam_probabilities=predictions[
                "spam_probability"
            ].astype(
                float
            ).tolist(),
        )
    )

    corrected_metrics = (
        calculate_metrics(
            labels=predictions[
                "corrected_label"
            ].astype(
                int
            ).tolist(),

            predictions=predictions[
                "predicted_label"
            ].astype(
                int
            ).tolist(),

            spam_probabilities=predictions[
                "spam_probability"
            ].astype(
                float
            ).tolist(),
        )
    )

    reviewed_mask = predictions[
        "manually_reviewed"
    ]

    reviewed_rows = predictions[
        reviewed_mask
    ]

    label_changes = int(
        reviewed_rows[
            "label_changed"
        ].sum()
    )

    original_ham_to_spam = int(
        (
            (
                reviewed_rows[
                    "true_label"
                ]
                == HAM_LABEL
            )
            &
            (
                reviewed_rows[
                    "corrected_label"
                ]
                == SPAM_LABEL
            )
        ).sum()
    )

    original_spam_to_ham = int(
        (
            (
                reviewed_rows[
                    "true_label"
                ]
                == SPAM_LABEL
            )
            &
            (
                reviewed_rows[
                    "corrected_label"
                ]
                == HAM_LABEL
            )
        ).sum()
    )

    model_actually_correct = int(
        reviewed_rows[
            "correct_after_review"
        ].sum()
    )

    true_model_errors = int(
        (
            ~reviewed_rows[
                "correct_after_review"
            ]
        ).sum()
    )

    print_metrics(
        title=(
            "ORIGINAL PRIVATE VALIDATION METRICS"
        ),
        metrics=original_metrics,
    )

    print_metrics(
        title=(
            "MANUALLY ADJUDICATED "
            "PRIVATE VALIDATION METRICS"
        ),
        metrics=corrected_metrics,
    )

    print(
        "\nManual adjudication summary"
    )

    print(
        "-" * 60
    )

    print(
        f"Reviewed disagreements: "
        f"{len(reviewed_rows)}"
    )

    print(
        f"Original labels changed: "
        f"{label_changes}"
    )

    print(
        f"Ham -> Spam corrections: "
        f"{original_ham_to_spam}"
    )

    print(
        f"Spam -> No Spam corrections: "
        f"{original_spam_to_ham}"
    )

    print(
        f"Cases where model was actually correct: "
        f"{model_actually_correct}"
    )

    print(
        f"Remaining genuine model errors: "
        f"{true_model_errors}"
    )

    print(
        "-" * 60
    )

    # Save complete adjudicated predictions.

    predictions.to_csv(
        ADJUDICATED_PREDICTIONS_FILE,
        index=False,
        encoding="utf-8-sig",
    )

    RESULTS_DIR.mkdir(
        parents=True,
        exist_ok=True,
    )

    results = {
        "evaluation_scope":
            (
                "private validation set with manual adjudication "
                "of every model-label disagreement"
            ),

        "important_note":
            (
                "Only model-label disagreements were manually "
                "reviewed. Examples where model and original label "
                "agreed retain their original label."
            ),

        "manual_review": {
            "reviewed_disagreements":
                int(
                    len(
                        reviewed_rows
                    )
                ),

            "original_labels_changed":
                label_changes,

            "ham_to_spam_corrections":
                original_ham_to_spam,

            "spam_to_ham_corrections":
                original_spam_to_ham,

            "model_actually_correct":
                model_actually_correct,

            "remaining_genuine_model_errors":
                true_model_errors,
        },

        "original_metrics":
            original_metrics,

        "adjudicated_metrics":
            corrected_metrics,
    }

    with open(
        CORRECTED_RESULTS_FILE,
        "w",
        encoding="utf-8",
    ) as file:

        json.dump(
            results,
            file,
            indent=2,
        )

    print(
        "\nAdjudicated predictions saved to:"
    )

    print(
        ADJUDICATED_PREDICTIONS_FILE
    )

    print(
        "\nCorrected metrics saved to:"
    )

    print(
        CORRECTED_RESULTS_FILE
    )


def parse_arguments():
    """
    Parse command-line mode.
    """

    parser = argparse.ArgumentParser(
        description=(
            "Prepare or score the complete private "
            "validation manual review."
        )
    )

    parser.add_argument(
        "mode",
        choices=[
            "prepare",
            "score",
        ],
        help=(
            "prepare creates the complete review CSV; "
            "score calculates metrics after review."
        ),
    )

    return parser.parse_args()


def main() -> None:
    """
    Run the requested review operation.
    """

    arguments = (
        parse_arguments()
    )

    if arguments.mode == "prepare":

        prepare_review_file()

    elif arguments.mode == "score":

        score_completed_review()


if __name__ == "__main__":
    main()